import { FoodItem } from '@/types/nutrition';

// 中国常见零食营养数据
// 数据来源：食品包装营养标签、中国食物成分表
export const SNACK_FOODS: FoodItem[] = [
  // ==================== 坚果瓜子类 ====================
  {
    id: 'snack-guazi-kuihuazi',
    name: '葵花籽（原味带壳）',
    category: 'snack',
    nutrients: {
      calories: 597,
      protein: 23.9,
      carbs: 16.7,
      fat: 52.8,
      fiber: 5.5,
    },
    servingSize: 50,
    servingUnit: '一小把（50g）',
    tags: ['瓜子', '葵花籽', '坚果', '零食'],
  },
  {
    id: 'snack-guazi-xiguazi',
    name: '西瓜子（原味带壳）',
    category: 'snack',
    nutrients: {
      calories: 556,
      protein: 32.7,
      carbs: 13.0,
      fat: 44.8,
      fiber: 4.5,
    },
    servingSize: 50,
    servingUnit: '一小把（50g）',
    tags: ['瓜子', '西瓜子', '坚果', '零食'],
  },
  {
    id: 'snack-guazi-nanguazi',
    name: '南瓜子（原味）',
    category: 'snack',
    nutrients: {
      calories: 566,
      protein: 33.2,
      carbs: 4.5,
      fat: 48.1,
      fiber: 6.0,
    },
    servingSize: 30,
    servingUnit: '一小把（30g）',
    tags: ['瓜子', '南瓜子', '坚果', '零食', '高蛋白'],
  },

  // ==================== 肉类零食 ====================
  {
    id: 'snack-niurougan',
    name: '牛肉干（五香）',
    category: 'snack',
    nutrients: {
      calories: 550,
      protein: 45.6,
      carbs: 15.0,
      fat: 32.0,
      sodium: 2100,
    },
    servingSize: 50,
    servingUnit: '一包（50g）',
    tags: ['牛肉干', '肉干', '高蛋白', '零食'],
  },
  {
    id: 'snack-niurougan-spicy',
    name: '牛肉干（麻辣）',
    category: 'snack',
    nutrients: {
      calories: 560,
      protein: 44.0,
      carbs: 18.0,
      fat: 33.5,
      sodium: 2300,
    },
    servingSize: 50,
    servingUnit: '一包（50g）',
    tags: ['牛肉干', '肉干', '高蛋白', '麻辣', '零食'],
  },
  {
    id: 'snack-yabo',
    name: '鸭脖（麻辣）',
    brand: '绝味/周黑鸭',
    category: 'snack',
    nutrients: {
      calories: 178,
      protein: 19.7,
      carbs: 3.5,
      fat: 9.8,
      sodium: 1800,
    },
    servingSize: 150,
    servingUnit: '一份（150g）',
    tags: ['鸭脖', '卤味', '麻辣', '绝味', '周黑鸭'],
  },
  {
    id: 'snack-yachi',
    name: '鸭翅（麻辣）',
    brand: '绝味/周黑鸭',
    category: 'snack',
    nutrients: {
      calories: 223,
      protein: 17.3,
      carbs: 2.8,
      fat: 16.2,
      sodium: 1650,
    },
    servingSize: 120,
    servingUnit: '两只（120g）',
    tags: ['鸭翅', '卤味', '麻辣', '零食'],
  },
  {
    id: 'snack-yasuogu',
    name: '鸭锁骨（麻辣）',
    brand: '绝味/周黑鸭',
    category: 'snack',
    nutrients: {
      calories: 195,
      protein: 16.8,
      carbs: 4.2,
      fat: 12.5,
      sodium: 1750,
    },
    servingSize: 150,
    servingUnit: '一份（150g）',
    tags: ['鸭锁骨', '卤味', '麻辣', '零食'],
  },
  {
    id: 'snack-fenzhengrou',
    name: '凤爪（泡椒）',
    category: 'snack',
    nutrients: {
      calories: 196,
      protein: 17.5,
      carbs: 6.2,
      fat: 11.8,
      sodium: 1600,
    },
    servingSize: 100,
    servingUnit: '一包（100g）',
    tags: ['凤爪', '鸡爪', '泡椒', '零食'],
  },

  // ==================== 辣条类 ====================
  {
    id: 'snack-latiao-weilong',
    name: '卫龙大面筋',
    brand: '卫龙',
    category: 'snack',
    nutrients: {
      calories: 490,
      protein: 8.5,
      carbs: 50.0,
      fat: 28.0,
      sodium: 3500,
    },
    servingSize: 65,
    servingUnit: '一包（65g）',
    tags: ['辣条', '卫龙', '大面筋', '零食', '高钠'],
  },
  {
    id: 'snack-latiao-small',
    name: '小辣条',
    category: 'snack',
    nutrients: {
      calories: 470,
      protein: 7.0,
      carbs: 55.0,
      fat: 24.0,
      sodium: 3200,
    },
    servingSize: 25,
    servingUnit: '一小包（25g）',
    tags: ['辣条', '小辣条', '零食', '高钠'],
  },
  {
    id: 'snack-latiao-kowei',
    name: '亲嘴烧',
    brand: '卫龙',
    category: 'snack',
    nutrients: {
      calories: 505,
      protein: 6.5,
      carbs: 52.0,
      fat: 29.5,
      sodium: 2800,
    },
    servingSize: 28,
    servingUnit: '一包（28g）',
    tags: ['辣条', '卫龙', '亲嘴烧', '零食'],
  },

  // ==================== 薯片饼干类 ====================
  {
    id: 'snack-leshi-original',
    name: '乐事薯片（原味）',
    brand: '乐事',
    category: 'snack',
    nutrients: {
      calories: 536,
      protein: 6.2,
      carbs: 52.0,
      fat: 33.5,
      sodium: 550,
    },
    servingSize: 70,
    servingUnit: '一袋（70g）',
    tags: ['薯片', '乐事', '原味', '零食'],
  },
  {
    id: 'snack-leshi-tomato',
    name: '乐事薯片（番茄味）',
    brand: '乐事',
    category: 'snack',
    nutrients: {
      calories: 530,
      protein: 5.8,
      carbs: 54.0,
      fat: 32.0,
      sodium: 620,
    },
    servingSize: 70,
    servingUnit: '一袋（70g）',
    tags: ['薯片', '乐事', '番茄', '零食'],
  },
  {
    id: 'snack-soda-biscuit',
    name: '苏打饼干（咸味）',
    category: 'snack',
    nutrients: {
      calories: 408,
      protein: 8.5,
      carbs: 76.0,
      fat: 8.2,
      sodium: 920,
    },
    servingSize: 100,
    servingUnit: '一包（100g）',
    tags: ['饼干', '苏打饼干', '咸', '零食'],
  },
  {
    id: 'snack-oreo',
    name: '奥利奥夹心饼干',
    brand: '奥利奥',
    category: 'snack',
    nutrients: {
      calories: 484,
      protein: 5.3,
      carbs: 67.0,
      fat: 21.5,
      sugar: 35.0,
    },
    servingSize: 97,
    servingUnit: '一袋（97g）',
    tags: ['饼干', '奥利奥', '夹心', '甜', '零食'],
  },

  // ==================== 传统零食 ====================
  {
    id: 'snack-huamei',
    name: '话梅',
    category: 'snack',
    nutrients: {
      calories: 168,
      protein: 1.2,
      carbs: 38.0,
      fat: 0.5,
      sodium: 5800,
    },
    servingSize: 30,
    servingUnit: '一小包（30g）',
    tags: ['话梅', '蜜饯', '酸', '零食', '高钠'],
  },
  {
    id: 'snack-mangogan',
    name: '芒果干',
    category: 'snack',
    nutrients: {
      calories: 355,
      protein: 1.8,
      carbs: 84.0,
      fat: 1.0,
      sugar: 70.0,
    },
    servingSize: 50,
    servingUnit: '一包（50g）',
    tags: ['芒果干', '果干', '甜', '零食'],
  },
  {
    id: 'snack-shan-zha-pian',
    name: '山楂片',
    category: 'snack',
    nutrients: {
      calories: 306,
      protein: 0.5,
      carbs: 76.0,
      fat: 0.2,
      sugar: 60.0,
    },
    servingSize: 50,
    servingUnit: '一卷（50g）',
    tags: ['山楂', '山楂片', '酸甜', '零食'],
  },

  // ==================== 膨化食品 ====================
  {
    id: 'snack-xiatiao',
    name: '虾条',
    category: 'snack',
    nutrients: {
      calories: 510,
      protein: 5.5,
      carbs: 60.0,
      fat: 27.0,
      sodium: 780,
    },
    servingSize: 45,
    servingUnit: '一袋（45g）',
    tags: ['虾条', '膨化', '零食'],
  },
  {
    id: 'snack-wangwang-xuebing',
    name: '旺旺雪饼',
    brand: '旺旺',
    category: 'snack',
    nutrients: {
      calories: 435,
      protein: 6.5,
      carbs: 82.0,
      fat: 8.5,
      sodium: 450,
    },
    servingSize: 84,
    servingUnit: '一袋（84g）',
    tags: ['雪饼', '旺旺', '米饼', '零食'],
  },
  {
    id: 'snack-wangwang-xianbei',
    name: '旺旺仙贝',
    brand: '旺旺',
    category: 'snack',
    nutrients: {
      calories: 470,
      protein: 5.8,
      carbs: 75.0,
      fat: 16.0,
      sodium: 520,
    },
    servingSize: 56,
    servingUnit: '一袋（56g）',
    tags: ['仙贝', '旺旺', '米饼', '零食'],
  },
  {
    id: 'snack-guoliduo',
    name: '好丽友薯愿',
    brand: '好丽友',
    category: 'snack',
    nutrients: {
      calories: 490,
      protein: 4.5,
      carbs: 64.0,
      fat: 24.0,
      sodium: 480,
    },
    servingSize: 104,
    servingUnit: '一筒（104g）',
    tags: ['薯片', '好丽友', '薯愿', '零食'],
  },

  // ==================== 豆干豆腐类零食 ====================
  {
    id: 'snack-dougan-spicy',
    name: '麻辣豆干',
    category: 'snack',
    nutrients: {
      calories: 240,
      protein: 18.5,
      carbs: 8.0,
      fat: 15.0,
      sodium: 1200,
    },
    servingSize: 100,
    servingUnit: '一包（100g）',
    tags: ['豆干', '麻辣', '豆腐', '零食', '高蛋白'],
  },
  {
    id: 'snack-dougan-wuxiang',
    name: '五香豆干',
    category: 'snack',
    nutrients: {
      calories: 210,
      protein: 20.0,
      carbs: 5.5,
      fat: 12.5,
      sodium: 900,
    },
    servingSize: 100,
    servingUnit: '一包（100g）',
    tags: ['豆干', '五香', '豆腐', '零食', '高蛋白'],
  },
];
