import { FoodItem } from '@/types/nutrition';

// 中国常见烘焙食品营养数据
// 数据来源：食品包装营养标签、中国食物成分表
export const BAKERY_FOODS: FoodItem[] = [
  // ==================== 面包类 ====================
  {
    id: 'bakery-bread-cream',
    name: '奶油面包',
    category: 'bakery',
    nutrients: {
      calories: 320,
      protein: 8.2,
      carbs: 48.0,
      fat: 10.5,
      sugar: 15.0,
    },
    servingSize: 80,
    servingUnit: '一个（80g）',
    tags: ['面包', '奶油', '烘焙', '早餐'],
  },
  {
    id: 'bakery-bread-boluo',
    name: '菠萝包',
    category: 'bakery',
    nutrients: {
      calories: 345,
      protein: 7.5,
      carbs: 52.0,
      fat: 12.0,
      sugar: 18.0,
    },
    servingSize: 90,
    servingUnit: '一个（90g）',
    tags: ['面包', '菠萝包', '港式', '烘焙'],
  },
  {
    id: 'bakery-bread-rousong',
    name: '肉松面包',
    category: 'bakery',
    nutrients: {
      calories: 310,
      protein: 10.5,
      carbs: 42.0,
      fat: 11.5,
    },
    servingSize: 85,
    servingUnit: '一个（85g）',
    tags: ['面包', '肉松', '烘焙', '咸味'],
  },
  {
    id: 'bakery-bread-yerong',
    name: '椰蓉面包',
    category: 'bakery',
    nutrients: {
      calories: 365,
      protein: 7.0,
      carbs: 50.0,
      fat: 15.0,
      sugar: 20.0,
    },
    servingSize: 80,
    servingUnit: '一个（80g）',
    tags: ['面包', '椰蓉', '烘焙', '甜'],
  },
  {
    id: 'bakery-bread-toast',
    name: '吐司面包',
    category: 'bakery',
    nutrients: {
      calories: 270,
      protein: 8.0,
      carbs: 50.0,
      fat: 4.5,
    },
    servingSize: 100,
    servingUnit: '两片（100g）',
    tags: ['面包', '吐司', '土司', '烘焙', '早餐'],
  },
  {
    id: 'bakery-croissant',
    name: '可颂/羊角面包',
    category: 'bakery',
    nutrients: {
      calories: 406,
      protein: 8.2,
      carbs: 46.0,
      fat: 21.0,
      saturatedFat: 12.0,
    },
    servingSize: 60,
    servingUnit: '一个（60g）',
    tags: ['可颂', '羊角包', '法式', '烘焙', '高热量'],
  },

  // ==================== 蛋糕类 ====================
  {
    id: 'bakery-cake-cream',
    name: '奶油蛋糕',
    category: 'bakery',
    nutrients: {
      calories: 380,
      protein: 5.5,
      carbs: 42.0,
      fat: 21.0,
      sugar: 28.0,
    },
    servingSize: 100,
    servingUnit: '一块（100g）',
    tags: ['蛋糕', '奶油', '甜点', '生日蛋糕', '高热量'],
  },
  {
    id: 'bakery-cake-chiffon',
    name: '戚风蛋糕',
    category: 'bakery',
    nutrients: {
      calories: 280,
      protein: 6.5,
      carbs: 38.0,
      fat: 11.5,
      sugar: 22.0,
    },
    servingSize: 80,
    servingUnit: '一块（80g）',
    tags: ['蛋糕', '戚风', '甜点', '烘焙'],
  },
  {
    id: 'bakery-swissroll',
    name: '瑞士卷',
    category: 'bakery',
    nutrients: {
      calories: 320,
      protein: 5.8,
      carbs: 45.0,
      fat: 13.0,
      sugar: 25.0,
    },
    servingSize: 80,
    servingUnit: '一卷（80g）',
    tags: ['蛋糕', '瑞士卷', '甜点', '卷蛋糕'],
  },
  {
    id: 'bakery-cake-mille',
    name: '千层蛋糕',
    category: 'bakery',
    nutrients: {
      calories: 420,
      protein: 5.0,
      carbs: 35.0,
      fat: 28.0,
      sugar: 20.0,
    },
    servingSize: 120,
    servingUnit: '一块（120g）',
    tags: ['蛋糕', '千层', '甜点', '高热量', '网红'],
  },
  {
    id: 'bakery-mousse',
    name: '慕斯蛋糕',
    category: 'bakery',
    nutrients: {
      calories: 295,
      protein: 4.5,
      carbs: 28.0,
      fat: 18.0,
      sugar: 22.0,
    },
    servingSize: 100,
    servingUnit: '一块（100g）',
    tags: ['蛋糕', '慕斯', '甜点', '冷藏'],
  },
  {
    id: 'bakery-tiramisu',
    name: '提拉米苏',
    category: 'bakery',
    nutrients: {
      calories: 350,
      protein: 5.5,
      carbs: 32.0,
      fat: 22.0,
      sugar: 24.0,
    },
    servingSize: 120,
    servingUnit: '一块（120g）',
    tags: ['蛋糕', '提拉米苏', '意式', '甜点', '咖啡'],
  },

  // ==================== 中式糕点 - 月饼 ====================
  {
    id: 'bakery-mooncake-lotus',
    name: '莲蓉月饼',
    category: 'bakery',
    nutrients: {
      calories: 421,
      protein: 6.2,
      carbs: 58.0,
      fat: 18.5,
      sugar: 35.0,
    },
    servingSize: 125,
    servingUnit: '一个（125g）',
    tags: ['月饼', '莲蓉', '中秋', '传统', '高热量'],
  },
  {
    id: 'bakery-mooncake-wuren',
    name: '五仁月饼',
    category: 'bakery',
    nutrients: {
      calories: 435,
      protein: 8.5,
      carbs: 52.0,
      fat: 22.0,
      sugar: 28.0,
    },
    servingSize: 125,
    servingUnit: '一个（125g）',
    tags: ['月饼', '五仁', '中秋', '传统'],
  },
  {
    id: 'bakery-mooncake-dousha',
    name: '豆沙月饼',
    category: 'bakery',
    nutrients: {
      calories: 405,
      protein: 7.0,
      carbs: 60.0,
      fat: 15.5,
      sugar: 38.0,
    },
    servingSize: 125,
    servingUnit: '一个（125g）',
    tags: ['月饼', '豆沙', '红豆', '中秋', '传统'],
  },
  {
    id: 'bakery-mooncake-snow',
    name: '冰皮月饼',
    category: 'bakery',
    nutrients: {
      calories: 280,
      protein: 4.0,
      carbs: 45.0,
      fat: 9.0,
      sugar: 25.0,
    },
    servingSize: 60,
    servingUnit: '一个（60g）',
    tags: ['月饼', '冰皮', '中秋', '冷藏', '低卡'],
  },

  // ==================== 中式糕点 - 其他 ====================
  {
    id: 'bakery-bindougao',
    name: '绿豆糕',
    category: 'bakery',
    nutrients: {
      calories: 350,
      protein: 6.5,
      carbs: 65.0,
      fat: 7.0,
      sugar: 35.0,
    },
    servingSize: 50,
    servingUnit: '两块（50g）',
    tags: ['绿豆糕', '中式', '传统', '糕点'],
  },
  {
    id: 'bakery-hongdougao',
    name: '红豆糕',
    category: 'bakery',
    nutrients: {
      calories: 340,
      protein: 5.8,
      carbs: 68.0,
      fat: 5.5,
      sugar: 38.0,
    },
    servingSize: 50,
    servingUnit: '两块（50g）',
    tags: ['红豆糕', '中式', '传统', '糕点'],
  },
  {
    id: 'bakery-danta',
    name: '蛋挞',
    category: 'bakery',
    nutrients: {
      calories: 285,
      protein: 5.5,
      carbs: 28.0,
      fat: 17.0,
      sugar: 15.0,
    },
    servingSize: 50,
    servingUnit: '一个（50g）',
    tags: ['蛋挞', '港式', '甜点', '烘焙'],
  },
  {
    id: 'bakery-danta-portuguese',
    name: '葡式蛋挞',
    category: 'bakery',
    nutrients: {
      calories: 320,
      protein: 5.0,
      carbs: 30.0,
      fat: 20.0,
      sugar: 18.0,
    },
    servingSize: 55,
    servingUnit: '一个（55g）',
    tags: ['蛋挞', '葡式', '甜点', '焦糖'],
  },

  // ==================== 传统点心 ====================
  {
    id: 'bakery-mahua',
    name: '麻花',
    category: 'bakery',
    nutrients: {
      calories: 524,
      protein: 8.0,
      carbs: 58.0,
      fat: 28.5,
    },
    servingSize: 60,
    servingUnit: '一根（60g）',
    tags: ['麻花', '传统', '油炸', '点心', '高热量'],
  },
  {
    id: 'bakery-sachima',
    name: '沙琪玛',
    category: 'bakery',
    nutrients: {
      calories: 470,
      protein: 6.5,
      carbs: 62.0,
      fat: 22.0,
      sugar: 28.0,
    },
    servingSize: 45,
    servingUnit: '一块（45g）',
    tags: ['沙琪玛', '传统', '甜', '点心'],
  },
  {
    id: 'bakery-laopobng',
    name: '老婆饼',
    category: 'bakery',
    nutrients: {
      calories: 395,
      protein: 5.0,
      carbs: 55.0,
      fat: 17.0,
      sugar: 22.0,
    },
    servingSize: 60,
    servingUnit: '一个（60g）',
    tags: ['老婆饼', '广式', '传统', '点心'],
  },
  {
    id: 'bakery-danhuangsu',
    name: '蛋黄酥',
    category: 'bakery',
    nutrients: {
      calories: 410,
      protein: 7.5,
      carbs: 45.0,
      fat: 22.5,
      cholesterol: 180,
    },
    servingSize: 55,
    servingUnit: '一个（55g）',
    tags: ['蛋黄酥', '中式', '酥皮', '点心', '高热量'],
  },
  {
    id: 'bakery-maci',
    name: '马卡龙',
    category: 'bakery',
    nutrients: {
      calories: 400,
      protein: 5.0,
      carbs: 70.0,
      fat: 12.0,
      sugar: 58.0,
    },
    servingSize: 30,
    servingUnit: '两个（30g）',
    tags: ['马卡龙', '法式', '甜点', '高糖'],
  },
  {
    id: 'bakery-puff',
    name: '泡芙',
    category: 'bakery',
    nutrients: {
      calories: 285,
      protein: 5.5,
      carbs: 25.0,
      fat: 18.0,
      sugar: 15.0,
    },
    servingSize: 60,
    servingUnit: '一个（60g）',
    tags: ['泡芙', '奶油', '甜点', '烘焙'],
  },
];
