import { FoodItem } from '@/types/nutrition';

// 中国常见零食营养数据
// 数据来源：食品包装营养标签、中国食物成分表
export const SNACK_FOODS: FoodItem[] = [
  // ==================== 坚果瓜子类 ====================
  {
    id: 'snack-guazi-kuihuazi',
    name: '葵花籽（原味带壳）',
    category: 'snack',
    nutrients: {
      calories: 597,
      protein: 23.9,
      carbs: 16.7,
      fat: 52.8,
      fiber: 5.5,
    },
    servingSize: 50,
    servingUnit: '一小把（50g）',
    tags: ['瓜子', '葵花籽', '坚果', '零食'],
  },
  {
    id: 'snack-guazi-xiguazi',
    name: '西瓜子（原味带壳）',
    category: 'snack',
    nutrients: {
      calories: 556,
      protein: 32.7,
      carbs: 13.0,
      fat: 44.8,
      fiber: 4.5,
    },
    servingSize: 50,
    servingUnit: '一小把（50g）',
    tags: ['瓜子', '西瓜子', '坚果', '零食'],
  },
  {
    id: 'snack-guazi-nanguazi',
    name: '南瓜子（原味）',
    category: 'snack',
    nutrients: {
      calories: 566,
      protein: 33.2,
      carbs: 4.5,
      fat: 48.1,
      fiber: 6.0,
    },
    servingSize: 30,
    servingUnit: '一小把（30g）',
    tags: ['瓜子', '南瓜子', '坚果', '零食', '高蛋白'],
  },

  // ==================== 肉类零食 ====================
  {
    id: 'snack-niurougan',
    name: '牛肉干（五香）',
    category: 'snack',
    nutrients: {
      calories: 550,
      protein: 45.6,
      carbs: 15.0,
      fat: 32.0,
      sodium: 2100,
    },
    servingSize: 50,
    servingUnit: '一包（50g）',
    tags: ['牛肉干', '肉干', '高蛋白', '零食'],
  },
  {
    id: 'snack-niurougan-spicy',
    name: '牛肉干（麻辣）',
    category: 'snack',
    nutrients: {
      calories: 560,
      protein: 44.0,
      carbs: 18.0,
      fat: 33.5,
      sodium: 2300,
    },
    servingSize: 50,
    servingUnit: '一包（50g）',
    tags: ['牛肉干', '肉干', '高蛋白', '麻辣', '零食'],
  },
  {
    id: 'snack-yabo',
    name: '鸭脖（麻辣）',
    brand: '绝味/周黑鸭',
    category: 'snack',
    nutrients: {
      calories: 178,
      protein: 19.7,
      carbs: 3.5,
      fat: 9.8,
      sodium: 1800,
    },
    servingSize: 150,
    servingUnit: '一份（150g）',
    tags: ['鸭脖', '卤味', '麻辣', '绝味', '周黑鸭'],
  },
  {
    id: 'snack-yachi',
    name: '鸭翅（麻辣）',
    brand: '绝味/周黑鸭',
    category: 'snack',
    nutrients: {
      calories: 223,
      protein: 17.3,
      carbs: 2.8,
      fat: 16.2,
      sodium: 1650,
    },
    servingSize: 120,
    servingUnit: '两只（120g）',
    tags: ['鸭翅', '卤味', '麻辣', '零食'],
  },
  {
    id: 'snack-yasuogu',
    name: '鸭锁骨（麻辣）',
    brand: '绝味/周黑鸭',
    category: 'snack',
    nutrients: {
      calories: 195,
      protein: 16.8,
      carbs: 4.2,
      fat: 12.5,
      sodium: 1750,
    },
    servingSize: 150,
    servingUnit: '一份（150g）',
    tags: ['鸭锁骨', '卤味', '麻辣', '零食'],
  },
  {
    id: 'snack-fenzhengrou',
    name: '凤爪（泡椒）',
    category: 'snack',
    nutrients: {
      calories: 196,
      protein: 17.5,
      carbs: 6.2,
      fat: 11.8,
      sodium: 1600,
    },
    servingSize: 100,
    servingUnit: '一包（100g）',
    tags: ['凤爪', '鸡爪', '泡椒', '零食'],
  },

  // ==================== 辣条类 ====================
  {
    id: 'snack-latiao-weilong',
    name: '卫龙大面筋',
    brand: '卫龙',
    category: 'snack',
    nutrients: {
      calories: 490,
      protein: 8.5,
      carbs: 50.0,
      fat: 28.0,
      sodium: 3500,
    },
    servingSize: 65,
    servingUnit: '一包（65g）',
    tags: ['辣条', '卫龙', '大面筋', '零食', '高钠'],
  },
  {
    id: 'snack-latiao-small',
    name: '小辣条',
    category: 'snack',
    nutrients: {
      calories: 470,
      protein: 7.0,
      carbs: 55.0,
      fat: 24.0,
      sodium: 3200,
    },
    servingSize: 25,
    servingUnit: '一小包（25g）',
    tags: ['辣条', '小辣条', '零食', '高钠'],
  },
  {
    id: 'snack-latiao-kowei',
    name: '亲嘴烧',
    brand: '卫龙',
    category: 'snack',
    nutrients: {
      calories: 505,
      protein: 6.5,
      carbs: 52.0,
      fat: 29.5,
      sodium: 2800,
    },
    servingSize: 28,
    servingUnit: '一包（28g）',
    tags: ['辣条', '卫龙', '亲嘴烧', '零食'],
  },

  // ==================== 薯片饼干类 ====================
  {
    id: 'snack-leshi-original',
    name: '乐事薯片（原味）',
    brand: '乐事',
    category: 'snack',
    nutrients: {
      calories: 536,
      protein: 6.2,
      carbs: 52.0,
      fat: 33.5,
      sodium: 550,
    },
    servingSize: 70,
    servingUnit: '一袋（70g）',
    tags: ['薯片', '乐事', '原味', '零食'],
  },
  {
    id: 'snack-leshi-tomato',
    name: '乐事薯片（番茄味）',
    brand: '乐事',
    category: 'snack',
    nutrients: {
      calories: 530,
      protein: 5.8,
      carbs: 54.0,
      fat: 32.0,
      sodium: 620,
    },
    servingSize: 70,
    servingUnit: '一袋（70g）',
    tags: ['薯片', '乐事', '番茄', '零食'],
  },
  {
    id: 'snack-soda-biscuit',
    name: '苏打饼干（咸味）',
    category: 'snack',
    nutrients: {
      calories: 408,
      protein: 8.5,
      carbs: 76.0,
      fat: 8.2,
      sodium: 920,
    },
    servingSize: 100,
    servingUnit: '一包（100g）',
    tags: ['饼干', '苏打饼干', '咸', '零食'],
  },
  {
    id: 'snack-oreo',
    name: '奥利奥夹心饼干',
    brand: '奥利奥',
    category: 'snack',
    nutrients: {
      calories: 484,
      protein: 5.3,
      carbs: 67.0,
      fat: 21.5,
      sugar: 35.0,
    },
    servingSize: 97,
    servingUnit: '一袋（97g）',
    tags: ['饼干', '奥利奥', '夹心', '甜', '零食'],
  },

  // ==================== 传统零食 ====================
  {
    id: 'snack-huamei',
    name: '话梅',
    category: 'snack',
    nutrients: {
      calories: 168,
      protein: 1.2,
      carbs: 38.0,
      fat: 0.5,
      sodium: 5800,
    },
    servingSize: 30,
    servingUnit: '一小包（30g）',
    tags: ['话梅', '蜜饯', '酸', '零食', '高钠'],
  },
  {
    id: 'snack-mangogan',
    name: '芒果干',
    category: 'snack',
    nutrients: {
      calories: 355,
      protein: 1.8,
      carbs: 84.0,
      fat: 1.0,
      sugar: 70.0,
    },
    servingSize: 50,
    servingUnit: '一包（50g）',
    tags: ['芒果干', '果干', '甜', '零食'],
  },
  {
    id: 'snack-shan-zha-pian',
    name: '山楂片',
    category: 'snack',
    nutrients: {
      calories: 306,
      protein: 0.5,
      carbs: 76.0,
      fat: 0.2,
      sugar: 60.0,
    },
    servingSize: 50,
    servingUnit: '一卷（50g）',
    tags: ['山楂', '山楂片', '酸甜', '零食'],
  },

  // ==================== 膨化食品 ====================
  {
    id: 'snack-xiatiao',
    name: '虾条',
    category: 'snack',
    nutrients: {
      calories: 510,
      protein: 5.5,
      carbs: 60.0,
      fat: 27.0,
      sodium: 780,
    },
    servingSize: 45,
    servingUnit: '一袋（45g）',
    tags: ['虾条', '膨化', '零食'],
  },
  {
    id: 'snack-wangwang-xuebing',
    name: '旺旺雪饼',
    brand: '旺旺',
    category: 'snack',
    nutrients: {
      calories: 435,
      protein: 6.5,
      carbs: 82.0,
      fat: 8.5,
      sodium: 450,
    },
    servingSize: 84,
    servingUnit: '一袋（84g）',
    tags: ['雪饼', '旺旺', '米饼', '零食'],
  },
  {
    id: 'snack-wangwang-xianbei',
    name: '旺旺仙贝',
    brand: '旺旺',
    category: 'snack',
    nutrients: {
      calories: 470,
      protein: 5.8,
      carbs: 75.0,
      fat: 16.0,
      sodium: 520,
    },
    servingSize: 56,
    servingUnit: '一袋（56g）',
    tags: ['仙贝', '旺旺', '米饼', '零食'],
  },
  {
    id: 'snack-guoliduo',
    name: '好丽友薯愿',
    brand: '好丽友',
    category: 'snack',
    nutrients: {
      calories: 490,
      protein: 4.5,
      carbs: 64.0,
      fat: 24.0,
      sodium: 480,
    },
    servingSize: 104,
    servingUnit: '一筒（104g）',
    tags: ['薯片', '好丽友', '薯愿', '零食'],
  },

  // ==================== 豆干豆腐类零食 ====================
  {
    id: 'snack-dougan-spicy',
    name: '麻辣豆干',
    category: 'snack',
    nutrients: {
      calories: 240,
      protein: 18.5,
      carbs: 8.0,
      fat: 15.0,
      sodium: 1200,
    },
    servingSize: 100,
    servingUnit: '一包（100g）',
    tags: ['豆干', '麻辣', '豆腐', '零食', '高蛋白'],
  },
  {
    id: 'snack-dougan-wuxiang',
    name: '五香豆干',
    category: 'snack',
    nutrients: {
      calories: 210,
      protein: 20.0,
      carbs: 5.5,
      fat: 12.5,
      sodium: 900,
    },
    servingSize: 100,
    servingUnit: '一包（100g）',
    tags: ['豆干', '五香', '豆腐', '零食', '高蛋白'],
  },

  // ==================== 巧克力糖果类 ====================
  {
    id: 'snack-dove-milk',
    name: '德芙牛奶巧克力',
    brand: '德芙',
    category: 'snack',
    nutrients: {
      calories: 546,
      protein: 6.4,
      carbs: 57.4,
      fat: 32.0,
      sugar: 52.0,
    },
    servingSize: 42,
    servingUnit: '一条（42g）',
    tags: ['巧克力', '德芙', '牛奶巧克力', '甜食', '零食'],
  },
  {
    id: 'snack-dove-dark',
    name: '德芙醇黑巧克力（66%）',
    brand: '德芙',
    category: 'snack',
    nutrients: {
      calories: 548,
      protein: 5.3,
      carbs: 43.0,
      fat: 38.0,
      sugar: 28.0,
    },
    servingSize: 43,
    servingUnit: '一条（43g）',
    tags: ['巧克力', '德芙', '黑巧克力', '零食'],
  },
  {
    id: 'snack-snickers',
    name: '士力架',
    brand: '士力架',
    category: 'snack',
    nutrients: {
      calories: 479,
      protein: 8.5,
      carbs: 60.0,
      fat: 23.5,
      sugar: 48.0,
    },
    servingSize: 51,
    servingUnit: '一根（51g）',
    tags: ['士力架', '巧克力', '花生', '零食', '能量棒'],
  },
  {
    id: 'snack-white-rabbit',
    name: '大白兔奶糖',
    brand: '大白兔',
    category: 'snack',
    nutrients: {
      calories: 402,
      protein: 4.2,
      carbs: 77.0,
      fat: 8.2,
      sugar: 70.0,
    },
    servingSize: 14,
    servingUnit: '两颗约14g',
    tags: ['大白兔', '奶糖', '糖果', '零食'],
  },
  {
    id: 'snack-pocky',
    name: '格力高百奇（巧克力）',
    brand: '格力高',
    category: 'snack',
    nutrients: {
      calories: 476,
      protein: 7.6,
      carbs: 65.0,
      fat: 21.0,
      sugar: 30.0,
    },
    servingSize: 47,
    servingUnit: '一盒（47g）',
    tags: ['百奇', '格力高', 'Pocky', '饼干棒', '零食'],
  },

  // ==================== 蛋糕点心类 ====================
  {
    id: 'snack-haoliyou-pie',
    name: '好丽友巧克力派',
    brand: '好丽友',
    category: 'snack',
    nutrients: {
      calories: 444,
      protein: 4.6,
      carbs: 58.0,
      fat: 22.0,
      sugar: 36.0,
    },
    servingSize: 36,
    servingUnit: '一个（36g）',
    tags: ['好丽友', '巧克力派', '蛋糕', '零食'],
  },
  {
    id: 'snack-orion-choco-pie',
    name: '好丽友蛋黄派',
    brand: '好丽友',
    category: 'snack',
    nutrients: {
      calories: 452,
      protein: 5.8,
      carbs: 55.0,
      fat: 24.0,
      sugar: 30.0,
    },
    servingSize: 33,
    servingUnit: '一个（33g）',
    tags: ['好丽友', '蛋黄派', '零食'],
  },

  // ==================== 三只松鼠/良品铺子系列 ====================
  {
    id: 'snack-sss-mix-nuts',
    name: '每日坚果（混合）',
    brand: '三只松鼠',
    category: 'snack',
    nutrients: {
      calories: 597,
      protein: 12.5,
      carbs: 27.0,
      fat: 50.0,
      fiber: 6.0,
    },
    servingSize: 25,
    servingUnit: '一小包（25g）',
    tags: ['坚果', '三只松鼠', '混合坚果', '每日坚果', '健康零食'],
  },
  {
    id: 'snack-liangpin-mix-nuts',
    name: '每日坚果（混合）',
    brand: '良品铺子',
    category: 'snack',
    nutrients: {
      calories: 590,
      protein: 12.0,
      carbs: 28.0,
      fat: 49.0,
      fiber: 5.5,
    },
    servingSize: 25,
    servingUnit: '一小包（25g）',
    tags: ['坚果', '良品铺子', '混合坚果', '每日坚果', '健康零食'],
  },
  {
    id: 'snack-sss-jerkies',
    name: '靖江猪肉脯',
    brand: '三只松鼠',
    category: 'snack',
    nutrients: {
      calories: 436,
      protein: 28.0,
      carbs: 44.0,
      fat: 15.0,
      sodium: 1800,
    },
    servingSize: 100,
    servingUnit: '一袋（100g）',
    tags: ['猪肉脯', '三只松鼠', '高蛋白', '零食', '肉干'],
  },
  {
    id: 'snack-liangpin-dried-tofu',
    name: '麻辣豆干',
    brand: '良品铺子',
    category: 'snack',
    nutrients: {
      calories: 255,
      protein: 19.0,
      carbs: 9.0,
      fat: 16.0,
      sodium: 1300,
    },
    servingSize: 100,
    servingUnit: '一包（100g）',
    tags: ['豆干', '良品铺子', '麻辣', '零食', '高蛋白'],
  },

  // ==================== 冰淇淋 ====================
  {
    id: 'snack-icecream-mengniu-lu',
    name: '随变冰淇淋（牛奶）',
    brand: '蒙牛',
    category: 'snack',
    nutrients: {
      calories: 200,
      protein: 2.5,
      carbs: 26.0,
      fat: 9.5,
      sugar: 22.0,
    },
    servingSize: 75,
    servingUnit: '一支（75g）',
    tags: ['冰淇淋', '蒙牛', '随变', '冷饮'],
  },
  {
    id: 'snack-icecream-yili-xu',
    name: '须尽欢冰淇淋',
    brand: '伊利',
    category: 'snack',
    nutrients: {
      calories: 196,
      protein: 3.0,
      carbs: 24.0,
      fat: 10.0,
      sugar: 20.0,
    },
    servingSize: 80,
    servingUnit: '一支（80g）',
    tags: ['冰淇淋', '伊利', '须尽欢', '冷饮'],
  },
  {
    id: 'snack-icecream-zhong-xue-gao',
    name: '钟薛高冰淇淋',
    brand: '钟薛高',
    category: 'snack',
    nutrients: {
      calories: 228,
      protein: 3.2,
      carbs: 28.0,
      fat: 11.5,
      sugar: 24.0,
    },
    servingSize: 80,
    servingUnit: '一支（80g）',
    tags: ['冰淇淋', '钟薛高', '雪糕', '冷饮'],
  },
  {
    id: 'snack-magnum',
    name: '梦龙冰淇淋（经典）',
    brand: '梦龙',
    category: 'snack',
    nutrients: {
      calories: 284,
      protein: 3.5,
      carbs: 30.0,
      fat: 16.5,
      sugar: 27.0,
    },
    servingSize: 86,
    servingUnit: '一支（86g）',
    tags: ['梦龙', '冰淇淋', '巧克力', '冷饮'],
  },
];
